# Generated by Django 4.0.6 on 2022-08-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name'], 'permissions': [('cancel_order', 'can cancel order'), ('view_history', 'can view history')]},
        ),
    ]
