# Generated by Django 4.0.6 on 2022-08-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name'], 'permissions': [('view_history', 'can view history')]},
        ),
    ]
